/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;

public class AppTest {
    @Test public void testMapBuilder() {
        try {
            WordLadder map = new WordLadder("dictionary.txt", 3);
        } catch (Exception e) {
            System.out.println("Map Builder failed.");
        }
    }

    @Test public void testWrongWord() {
        try {
            WordLadder map = new WordLadder("dictionary.txt", 3);
            assertEquals(false, map.testCheckWords("cat", "foot"));
            assertEquals(false, map.testCheckWords("cat", "cat"));
            assertEquals(false, map.testCheckWords("cat", "ca2"));
            assertEquals(true, map.testCheckWords("cat", "dog"));
        } catch (Exception e) {
            System.out.println("Map Builder failed.");
        }
    }

    @Test public void testStepNumber() {
        // WordMap map = new WordMap("dictionary.txt", 3);
    }
}
